# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5a0f80975830b523e8dac10a6d70488776cad798ad29861428553cb07f8a29ae5611819fae50e26a330e673f5db011ec9830b512585eddb8545108a2bd23dd52

test:
  secret_key_base: 9076a6b91b495cb6b3eaad07514e97e6934276034cc9c3736b115fe6bbb5a3bb2587fc1c05a09adf7d7a86e65cefc0c3d6cf2aecce02a8d756200ba925886476

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
